### ISSUE TITLE
Add download button with modal

### ISSUE THREAD

**Issue by udz-codes** [Tishasoumya-02/-Picturesque-Gallery#19]
When a user clicks on a picture, a modal opens. A download button can be added to make it easier to download pictures.

**Comment by udz-codes** [comment]
> When a user clicks on a picture, a modal opens. A download button can be added to make it easier to download pictures.

If you like the idea, I would like to work on this.

**Comment by Tishasoumya-02** [comment]
This appication does not require this feature. Thank you for your issue you can lookup for making some other changes in the application.
