### ISSUE TITLE
UI design update needed

### ISSUE THREAD

**Issue by mohittk** [Tishasoumya-02/-Picturesque-Gallery#3]
The website has to be more good looking. I can contribute in that case, can you assign me this? @Tishasoumya-02

**Comment by Tishasoumya-02** [comment]
Yes, the website design is not so authentic, feel free to open a PR.

**Comment by mohittk** [comment]
> Yes, the website design is not so authentic, feel free to open a PR.

Good to hear! assign me this one. in assign section.

**Comment by juhiechandra** [comment]
Hello sir/ma'am, should I upload design in form of figma file? or directly code it? or both?

**Comment by Tishasoumya-02** [comment]
Both would be nice, first share the Figma file here or email, then you could proceed with the coding part.

**Comment by juhiechandra** [comment]
Sure thing! Thank you for assigning it to me. I will share the work as soon as the event begins.
