### ISSUE TITLE
Suggest limiting the first API call

### ISSUE THREAD

**Issue by EmmaDawsonDev** [Tishasoumya-02/-Picturesque-Gallery#4]
the first API call fetches 500 items which makes the site really slow to load. It would be worth limiting this to just a few as they're going to be random and not what people are searching for.

**Comment by Tishasoumya-02** [comment]
Yes, could do that. Mostly I was thinking of infinite scrolling but was not able to make that happen

**Comment by codeantik** [comment]
I can do this, Assign me the issue

**Comment by codeantik** [comment]
I have fixed this issue, You may merge my PR
