### ISSUE TITLE
Lists should only contain list items

### ISSUE THREAD

**Issue by EmmaDawsonDev** [Tishasoumya-02/-Picturesque-Gallery#5]
You have a ul tag to show all the images which doesn't render any li tags inside it. Either render all images as list items and remove styling or remove ul tag and replace with a section tag instead. This would be a good first issue for hacktoberfest :)

**Comment by Tishasoumya-02** [comment]
Yes

**Comment by saif-malik-01** [comment]
i want to work on it, please assign this to me.

**Comment by Tishasoumya-02** [comment]
Sure!
